"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CATALOG_TARGET_FIELDS = void 0;
exports.CATALOG_TARGET_FIELDS = [
    'ignore',
    'externalId',
    'sku',
    'barcode',
    'title',
    'handle',
    'description',
    'vendor',
    'productType',
    'price',
    'compareAtPrice',
    'cost',
    'currency',
    'inventoryQuantity',
    'inventoryTracker',
    'inventoryPolicy',
    'fulfillmentService',
    'requiresShipping',
    'taxable',
    'option1Name',
    'option1Value',
    'option2Name',
    'option2Value',
    'option3Name',
    'option3Value',
    'image',
    'imagePosition',
    'imageAlt',
    'tags',
    'weight',
    'weightUnit',
    'variantGrams',
    'giftCard',
    'seoTitle',
    'seoDescription',
    'status',
];
//# sourceMappingURL=index.js.map